apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app
spec:
  selector:
    matchLabels:
      app: my-first-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-first-app
    spec:
      containers:
        - image: mrkhadus/kubeapp:first
          name: demoapp
