apiVersion: v1
kind: Service
metadata:
  name: kubeapp-service
spec:
  selector:
    app: my-first-app
  ports:
  - protocol: 'TCP'
    port: 80
    targetPort: 8080
  # - protocol: 'TCP'
    # port: 443
    # targetPort: 443
  type: LoadBalancer

