apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: mrkhadus/network-users:ipdns
        env:
          - name: AUTH_ADDRESS
            #value: "10.99.246.122"  # will override AUTH_ADDRESS: auth ==> defined in docker compose
            value: "auth-service.default"   # core dns method to use only the <serviceName>.<namespace> to communicate to other service
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        # ports:
        # - containerPort: 8080
        imagePullPolicy: Always

